### PR TITLE
FIX: Avatar fallback in FeatureCreatorCard to show initials when no image provided

### LINKED ISSUE #712: Fix avatar fallback in FeatureCreatorCard to show initials when no image provided
## Description

The `FeatureCreatorCard` component in `apps/web/components/shared/feature-creator-card.tsx` currently conditionally renders the `UserAvatar` component only when `avatarUrl` is provided. This prevents the initials fallback from being displayed when no avatar URL is available, which undermines the robust avatar display goals.

## Problem

Currently:
```tsx
{avatarUrl && (
  <UserAvatar
    src={avatarUrl}
    alt={`${name}'s avatar`}
    name={name}
    className="h-20 w-20"
  />
)}
```

This means when `avatarUrl` is undefined/empty, no avatar is shown at all, missing the opportunity to display user initials as a fallback.

## Expected Solution

Always render the `UserAvatar` component and let it handle the fallback internally:
```tsx
<UserAvatar
  src={avatarUrl || undefined}
  alt={`${name}'s avatar`}
  name={name}
  className="h-20 w-20"
/>
```

## Context

This issue was identified during the review of PR #632 which introduced the `UserAvatar` component and `getAvatarFallback` utility to provide robust avatar fallbacks throughout the application.

## References

- PR: https://github.com/kindfi-org/kindfi/pull/632
- Comment: https://github.com/kindfi-org/kindfi/pull/632#discussion_r2289226642

## Labels

Good first issue, beginner-friendly

### PR DESCRIPTION
**Pull request by EmmanuelOloke**
This PR:

- Fixes the conditional rendering issue with the `FeatureCreatorCard` component.
- Improves the `getAvatarFallback` utility function to allow for proper initials as a fallback.

### Related Issues
Closes #712 

## Summary by CodeRabbit

- **New Features**
  - Avatars now render consistently even when no image is provided, showing an auto-generated placeholder instead of being omitted.
  - Smarter fallback initials: handles single and multi-word names, ignores extra spaces, and shows two-letter initials when possible (e.g., “John Doe” → “JD”, “Madonna” → “MA”).
  - Creator cards always display an avatar, improving visual consistency across list and profile views.

### CODE REVIEW

File: apps/web/components/shared/feature-creator-card.tsx [hunk 1]
```diff
@@ -49,14 +49,12 @@ export const FeatureCreatorCard = ({
...
-					{avatarUrl && (
-						<UserAvatar
-							src={avatarUrl}
-							alt={`${name}'s avatar`}
-							name={name}
-							className="h-20 w-20"
-						/>
-					)}
+					<UserAvatar
+						src={avatarUrl || undefined}
```
Comment (AndlerRL) [inline apps/web/components/shared/feature-creator-card.tsx:53]: If the `src` expects to be `undefined` and the `avatarUrl` can be `undefined` hence it is OK to just do `src={avatarUrl}`

**Review by AndlerRL — CHANGES_REQUESTED** [review]
Looking good 👍 I see a few tweaks and @coderabbitai feedbacks that we can do before to merge.

> You can always take coderabbitai review before our human reviews, only if they are within scope.

File: apps/web/components/shared/feature-creator-card.tsx (hunk 1 above)
Comment (EmmanuelOloke) [reply apps/web/components/shared/feature-creator-card.tsx]: Oh I see. Nice catch, I've removed the explicit undefined passing now.

**Review by Bran18 — APPROVED** [review]
LGTM
