### PR TITLE
fix: improve auth error handling

### LINKED ISSUE #22: Improve Authentication Error Handling
## Context
Current authentication error handling needs improvement to prevent information leakage and provide better user experience.

### Impact
- Prevents potential information disclosure through error messages
- Improves user experience during auth failures
- Enhances security logging and monitoring

### Implementation Areas
- Review error handling in apps/web/app/auth/callback/route.ts
- Implement proper error messages
- Add logging for security events
- Handle edge cases gracefully

### References
- Original discussion: https://github.com/kindfi-org/kindfi/issues/8

/cc @AndlerRL

### PR DESCRIPTION
**Pull request by Benjtalkshow**
Fixes #22 
# Improve Authentication System Implementation - Work in Progress

## Overview
This pull request introduces the improvement of our authentication error handling system  and custom error handling. 

### 1. `app/auth/confirm/route.ts`
- Incorporates custom error handling and logging

### 2. `hooks/uae-auth-callback.ts`
- Implements a custom `use-auth-callback.ts` to handle all the auth related errors

### 4. `lib/auth/error-handler.ts`
- Implements `AuthErrorHandler` class for consistent error handling
- Defines error types and messages
- Provides methods for handling and logging authentication errors

### 5. `lib/auth/type.ts`
- Defines `AuthResponse` type for consistent authentication response structure

### 6. `lib/logger.ts`
- Implements a basic `Logger` class for consistent logging across the application

### 7. `app/actions.ts`
- Modified already exisiting server actions for authentication operations (sign up, sign in, sign out, etc.)
- Incorporates error handling and logging

### 8. `app/(auth)/login/page.tsx`
- Incorporates client side auth error handling
- Displays toast notifications for success and error cases

## Ongoing Work
- Refining error messages and improving error handling
- Implementing rate limiting
- Improving overall UX and accessibility of auth forms
- Documenting the authentication system and its usage

## Testing
- Conduct security audit of the authentication system

Please note that this PR is not ready for final review as it's still a work in progress. 
Feedback on the current implementation and architecture is welcome.

## Summary by CodeRabbit

- **New Features**
  - Enhanced authentication flows now deliver real-time, context-aware notifications for login, signup, and OTP verification, ensuring clearer feedback.
  - Global toast notifications provide immediate user feedback on errors and successful actions.
  - Updated UI transitions with new animation effects offer smoother and more engaging interactions across the application.

### CODE REVIEW

File: apps/web/components/base/toast.tsx
Comment (AndlerRL) [inline apps/web/components/base/toast.tsx:1]: There is a toaster already, it is the `sonner.tsx` component. Double-check if we are duplicating the components for the same implementation of toasters. IF the intention is to create a toaster with alerts and history, it is better to keep the sonner component.

Again, I invite you to explore which one fits more. But I suggest always "sonner" component, it is more interactive and has more funcitonallity.

File: apps/web/hooks/use-toast.tsx
Comment (AndlerRL) [inline apps/web/hooks/use-toast.tsx:1]: Why there are 2 hooks with the same name? This one looks like a component.

Please remove.

File: apps/web/lib/auth/error-handler.ts [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+  INVALID_CODE = 'INVALID_CODE',
+  PASSWORD_MISMATCH = 'PASSWORD_MISMATCH',
+  WEAK_PASSWORD = 'WEAK_PASSWORD',
+  EMAIL_TAKEN = 'EMAIL_TAKEN',
+  RATE_LIMITED = 'RATE_LIMITED',
+  SESSION_EXPIRED = 'SESSION_EXPIRED',
+  INVALID_RESET_TOKEN = 'INVALID_RESET_TOKEN'
+}
+
+const ERROR_MESSAGES = {
```
Comment (AndlerRL) [inline apps/web/lib/auth/error-handler.ts:17]: Move error messages to the `lib/constants/errors.ts` file.

File: apps/web/lib/auth/error-handler.ts [hunk 2]
```diff
@@ -0,0 +1,76 @@
+import { Logger } from '~/lib/logger'
+import { AuthError } from '@supabase/supabase-js'
+import type { AuthResponse } from './type'
+
+enum AuthErrorType {
```
Comment (AndlerRL) [inline apps/web/lib/auth/error-handler.ts:5]: Move error messages to the `lib/types/auth/errors.ts` file or similar. It must be descriptive.

File: apps/web/lib/auth/type.ts
Comment (AndlerRL) [inline apps/web/lib/auth/type.ts:1]: you can rename it as either `index.ts` or add `auth.types.ts` and then an `index.ts` to export all related auth type files. Additionally, move this into the `lib/types` folder.

**Review by AndlerRL — COMMENTED** [review]
Hey @Benjtalkshow I know it is a Draft but I left some comments that you can take while finishing the task.

Thanks! 🙏

**Comment by Benjtalkshow** [comment]
> Hey @Benjtalkshow I know it is a Draft but I left some comments that you can take while finishing the task.
> 
> Thanks! 🙏

Alright. @AndlerRL 
Would be necessary to add late limiting? for multiple failed authentication attempts

File: apps/web/app/actions.ts [hunk 3]
```diff
@@ -2,118 +2,200 @@
...
+		if (error) {
+			return errorHandler.handleAuthError(error, 'reset_password')
+		}
+
+		return {
+			success: true,
+			message: 'Password updated successfully',
+			redirect: '/sign-in',
+		}
+	} catch (error: any) {
```
[the remark this answers is not in the document]
Comment (AndlerRL) [reply apps/web/app/actions.ts:167]: Always avoid to declare a TS definition directly the `catch` property. It is better to do:

```ts
try {
  // your code...
} catch (err) {
  const error = err as Error
  // rest of your code...
}
```

File: apps/web/lib/constants/animations.ts
Comment (AndlerRL) [inline apps/web/lib/constants/animations.ts:1]: Make sure we are not duplicating the definitions made at `lib/animations.ts` 👀 if we do, we can remove the other one and update the imports to this folder location. If it is partially, then move the non-defined objects to here and update the imports to this folder location.

File: apps/web/lib/types/auth/auth.types.ts [hunk 4]
```diff
@@ -0,0 +1,21 @@
...
+	UNAUTHORIZED = 'UNAUTHORIZED',
+	SERVER_ERROR = 'SERVER_ERROR',
+}
+
+export interface AuthResponse {
+	success: boolean
+	message: string
+	error?: string
+	redirect?: string
+}
```
[the remark this answers is not in the document]
Comment (AndlerRL) [reply apps/web/lib/types/auth/auth.types.ts:21]: This function definitions can go to `/lib/error.ts` file.

**Review by AndlerRL — CHANGES_REQUESTED** [review]
LGTM! Good way to create the error handling 👍 I left the coderabbitai feedbacks that you can take before to merge. I made some addtional comments too to take in consideration!

> 💡Even that the type could be obvious, it is always important to keep practice to define the TS in our code when working with TypeScript. Make sure to not over define the types though! Always define whenever it is required and use intrinsic definition as much as possible.

File: apps/web/lib/logger.ts [hunk 5]
```diff
@@ -0,0 +1,13 @@
...
+	}
+
+	warn(data: Record<string, any>) {
+		console.warn('[Warning]', JSON.stringify(data, null, 2))
+	}
+
+	info(data: Record<string, any>) {
+		console.info('[Info]', JSON.stringify(data, null, 2))
+	}
+}
```
[the remark this answers is not in the document]
Comment (AndlerRL) [reply apps/web/lib/logger.ts:13]: The interface definition can go to his related type file.

File: apps/web/lib/constants/animations.ts
Comment (Benjtalkshow) [reply apps/web/lib/constants/animations.ts:1]: Alright sir. Will make the requested changes soon. Thanks

File: apps/web/app/(auth-pages)/sign-in/page.tsx [hunk 6]
```diff
@@ -21,6 +30,35 @@ export default function Login() {
...
+			} else {
+				toast.success('You have successfully logged in.')
+				router.push(response.redirect || '/dashboard')
+			}
+		} catch (err) {
+			const error = err as Error
+			const errorResponse = handleClientAuthError(error)
+			setAuthResponse(errorResponse)
+			toast.error(errorResponse.message)
+		}
```
[the remark this answers is not in the document]
Comment (Benjtalkshow) [reply apps/web/app/(auth-pages)/sign-in/page.tsx:59]: @AndlerRL Please review. 
I would also love to work on any other security related issues. Thanks

**Review by AndlerRL — DISMISSED** [review]
LGTM! Thanks @Benjtalkshow for taking care the observations. Sure I will assign a new security task for you once I have one ready 🙂 merging!

**Comment by AndlerRL** [comment]
Hey @Benjtalkshow after approving I was checking the build for the webapp and I noticed that it is not going through. Can you check this in your end, please?



> 💡 to avoid this, next time, build the webapp locally by running `bun run build` in the web folder.

**Comment by Benjtalkshow** [comment]
> Hey @Benjtalkshow after approving I was checking the build for the webapp and I noticed that it is not going through. Can you check this in your end, please?
> 
> 
> 
> > 💡 to avoid this, next time, build the webapp locally by running `bun run build` in the web folder.

@AndlerRL 
Yeah, I noticed that all the build failures came from other contributors' tasks. It seems like theirs weren't built before deployment.
image

**Comment by Benjtalkshow** [comment]
> Hey @Benjtalkshow after approving I was checking the build for the webapp and I noticed that it is not going through. Can you check this in your end, please?
> 
> 
> 
> > 💡 to avoid this, next time, build the webapp locally by running `bun run build` in the web folder.

@AndlerRL 
I noticed that all the build failures came from other contributors' tasks. It seems like theirs weren't built before deployment.

**Comment by Benjtalkshow** [comment]
@AndlerRL 
I have fixed all the build issues. Looking forward to getting another security task. 
Thanks for your kind way of giving corrections. I so much appreciate your effort.
image

File: apps/web/app/auth/confirm/route.ts [hunk 7]
```diff
@@ -1,26 +1,69 @@
...
+
+      redirect(next)
+    } catch (error) {
+      logger.error({
+        eventType: 'UNEXPECTED_ERROR',
+        error: error instanceof Error ? error.message : 'Unknown error',
+      })
+      redirect('/error?reason=unexpected_error')
+    }
+  }
```
[the remark this answers is not in the document]
Comment (Bran18) [reply apps/web/app/auth/confirm/route.ts:60]: @coderabbitai create a new issue to address the suggestion and include the Improve error key matching logic too please

**Review by Bran18 — APPROVED** [review]
LGTM! Tks for taking care of the observation from Andler
